# Importación de librerias

In [622]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [624]:
import sys
sys.executable
sys.path.append('../')
from SRC import Limpieza as lp

In [ ]:
import openpyxl
openpyxl.__version__
pd.__version__

# Carga de datos #

# 1.Campañas de marketing #

# Columnas del dataset  #

age: La edad del cliente.

job: La ocupación o profesión del cliente.

marital: El estado civil del cliente.

education: El nivel educativo del cliente.

default: Indica si el cliente tiene algún historial de incumplimiento de pagos (1: Sí, 0: No).

housing: Indica si el cliente tiene un préstamo hipotecario (1: Sí, 0: No).

loan: Indica si el cliente tiene algún otro tipo de préstamo (1: Sí, 0: No).

contact: El método de contacto utilizado para comunicarse con el cliente.

duration: La duración en segundos de la última interacción con el cliente.

campaign: El número de contactos realizados durante esta campaña para este cliente.

pdays: Número de días que han pasado desde la última vez que se contactó con el cliente durante esta campaña.

previous: Número de veces que se ha contactado con el cliente antes de esta campaña.

poutcome: Resultado de la campaña de marketing anterior.

emp.var.rate: La tasa de variación del empleo.

cons.price.idx: El índice de precios al consumidor.

cons.conf.idx: El índice de confianza del consumidor.

euribor3m: La tasa de interés de referencia a tres meses.

nr.employed: El número de empleados.

y: Indica si el cliente ha suscrito un producto o servicio (Sí/No).

date: La fecha en la que se realizó la interacción con el cliente.


id_: Un identificador único para cada registro en el dataset.

In [ ]:
df_marketing = pd.read_csv('../Datos/raw/bank-additional.csv')

In [ ]:
df_marketing.head()

In [631]:
df_marketing.shape

(43000, 29)

In [630]:
df_marketing.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   unnamed:_0      43000 non-null  int64
 1   age             43000 non-null  int64
 2   job             43000 non-null  str
 3   marital         43000 non-null  str
 4   education       43000 non-null  str
 5   default         43000 non-null  object
 6   housing         43000 non-null  object
 7   loan            43000 non-null  object
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp_var_rate    43000 non-null  float64
 15  cons_price_idx  43000 non-null  float64
 16  cons_conf_idx   43000 non-null  str
 17  euribor3m       43000 non-null  object
 18  nr_employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  datetime64[us]
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id              43000 non-null  str
 24  date_missing    43000 non-null  int64
 25  date_imputed    43000 non-null  datetime64[us]
 26  year            43000 non-null  int32
 27  month           43000 non-null  int32
 28  weekday         43000 non-null  str
dtypes: datetime64[us](2), float64(4), int32(2), int64(7), object(4), str(10)
memory usage: 9.2+ MB

In [629]:
df_marketing.describe()

,unnamed:_0,age,duration,campaign,pdays,previous,emp_var_rate,cons_price_idx,date,latitude,longitude,date_missing,date_imputed,year,month
count,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,42752,43000.000000,43000.000000,43000.000000,43000,43000.000000,43000.000000
mean,20651.099047,39.741698,257.739279,2.567233,962.330953,0.174023,0.077128,93.576134,2017-07-01 19:55:11.676646,36.856697,-95.939067,0.005767,2017-07-01 20:13:13.004651,2017.001302,6.504930
min,0.000000,17.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,2015-01-01 00:00:00,24.396000,-124.997000,0.000000,2015-01-01 00:00:00,2015.000000,1.000000
25%,10381.750000,33.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,2016-04-01 00:00:00,30.614750,-110.494250,0.000000,2016-04-04 00:00:00,2016.000000,4.000000
50%,20642.500000,38.000000,179.000000,2.000000,999.000000,0.000000,1.100000,93.749000,2017-07-04 00:00:00,36.761000,-95.899500,0.000000,2017-07-04 00:00:00,2017.000000,7.000000
75%,30930.250000,46.000000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,2018-10-01 06:00:00,43.113250,-81.427750,0.000000,2018-09-30 00:00:00,2018.000000,9.000000
max,41187.000000,98.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,2019-12-31 00:00:00,49.384000,-66.937000,1.000000,2019-12-31 00:00:00,2019.000000,12.000000
std,11868.770913,9.817735,258.666033,2.772294,187.260394,0.497366,1.573898,0.576652,NaN,7.225948,16.752282,0.075725,NaN,1.410228,3.438965

In [ ]:
df_marketing.columns

In [627]:
df_marketing.columns = (
    df_marketing.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_')
        .str.replace('.', '_', regex=False)
)
df_marketing.columns

Index(['unnamed:_0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y', 'date', 'latitude',
       'longitude', 'id', 'date_missing', 'date_imputed', 'year', 'month',
       'weekday'],
      dtype='str')

In [ ]:
df_marketing.rename(columns={'id_': 'id'}, inplace=True)
df_marketing.columns

# Duplicados

In [628]:
df_marketing.duplicated().sum()

np.int64(0)

VALORES NULOS

In [ ]:
df_marketing.isnull().sum()

In [ ]:
""""mejor visualización de valores nulos para análisis exploratorio"""
df_marketing.isnull().sum()/len(df_marketing)*100

Se imputan los valores nulos de variables categóricas con 'unknown' debido a su bajo porcentaje de ausencia, evitando sesgos en el análisis.

In [ ]:
"""Manejo de valores nulos en variables categóricas"""

def categorical_cols(df, columnas):
    for col in columnas:
        df[col] = df[col].fillna('unknown')
    return df
 
categorical_cols_list = [
    'job',
    'marital',
    'education',
    'default',
    'housing',
    'loan'
]

In [ ]:
df_marketing = categorical_cols(df_marketing, categorical_cols_list)

In [ ]:
df_marketing.isnull().sum()

In [ ]:
"""Se completa el valor nulo de la variable 'euribor3m' con el dato faltante que es el mismo en todos los casos"""

df_marketing['euribor3m']= df_marketing ['euribor3m'].fillna(4.857)

In [ ]:
"""Se completa el valor nulo de la variable 'age' con la mediana de la misma"""

df_marketing['age'] = df_marketing['age'].fillna(df_marketing['age'].median())

In [ ]:
""" Se cambia el formato de la variable 'cons_price_idx' para convertirla a numérica """

df_marketing['cons_price_idx'] = df_marketing['cons_price_idx'].astype(str).str.replace(',', '.').str.strip()

df_marketing['cons_price_idx'] = pd.to_numeric(df_marketing['cons_price_idx'], errors='coerce')

In [ ]:
"""Se completa el valor nulo de la variable 'cons_price_idx' con la mediana de la misma"""

df_marketing['cons_price_idx'] = df_marketing['cons_price_idx'].fillna(df_marketing['cons_price_idx'].median())

In [ ]:
df_marketing.isnull().sum()

In [ ]:
"""Tramiento de columna date"""

df_marketing["date"].head()

In [ ]:
"""Creación de diccionario de meses"""
meses = {
    "enero": "01",
    "febrero": "02",
    "marzo": "03",
    "abril": "04",
    "mayo": "05",
    "junio": "06",
    "julio": "07",
    "agosto": "08",
    "septiembre": "09",
    "octubre": "10",
    "noviembre": "11",
    "diciembre": "12"
}

In [ ]:
"""Normalización de texto en columna date"""

df_marketing["date"] = (
    df_marketing["date"]
    .str.lower()
    .str.strip()
)

In [ ]:
"""Reemplazo de meses en texto por meses en número"""

for mes_texto, mes_num in meses.items():
    df_marketing["date"] = df_marketing["date"].str.replace(
        f"-{mes_texto}-",
        f"-{mes_num}-",
        regex=False
    )

In [ ]:
"""Verificación de cambios en columna date"""

df_marketing["date"].head()

In [ ]:
"""Convertir columna date a formato fecha"""

df_marketing["date"] = pd.to_datetime(
    df_marketing["date"],
    format="%d-%m-%Y",
    errors="coerce"
)
df_marketing["date"].head()

In [ ]:
df_marketing["date"].isna().sum()

Las fechas nulas no fueron eliminadas ya que pueden reflejar incidencias operativas en la campaña de marketing.
Se creó una variable indicadora para identificar estos casos y se imputó la fecha mediante la mediana únicamente para permitir el análisis temporal, preservando la información original.

In [ ]:
def impute_date_with_median(df, date_col):
    """
    Imputa valores nulos en una variable de fecha utilizando la mediana,
    creando previamente una variable indicadora y generando features temporales
    para análisis.
    """
    # Variable indicadora: 1 si la fecha es nula, 0 si no
    df[f'{date_col}_missing'] = df[date_col].isnull().astype(int)

    # Cálculo de la mediana
    fecha_mediana = df[date_col].median()

    # Imputación de la fecha
    df[f'{date_col}_imputed'] = df[date_col].fillna(fecha_mediana)

    # Variables temporales
    df['year'] = df[f'{date_col}_imputed'].dt.year
    df['month'] = df[f'{date_col}_imputed'].dt.month
    df['weekday'] = df[f'{date_col}_imputed'].dt.day_name()

    return df

In [ ]:
df_marketing = impute_date_with_median(df_marketing, 'date')
df_marketing[['date', 'date_missing', 'date_imputed', 'year', 'month', 'weekday']].head()

Normalizar datos

In [ ]:
"""Normalización de datos 1 y 0 por "yes" y "no" """

df_marketing["default"] = df_marketing["default"].replace({1.0: "yes", 0.0: "no"})
df_marketing["housing"] = df_marketing["housing"].replace({1.0: "yes", 0.0: "no"})
df_marketing["loan"] = df_marketing["loan"].replace({1.0: "yes", 0.0: "no"})

In [ ]:
"""Normalización de "age"""""

df_marketing["age"] = df_marketing["age"].astype(int)
df_marketing["age"].head()

In [ ]:
"""Normalización de "education" """

df_marketing["education"] = df_marketing["education"].replace({
    "basic.4y": "basic",
    "basic.6y": "basic",
    "basic.9y": "basic",
    "high.school": "high school",
    "illiterate": "unknown"
})
df_marketing["education"].value_counts()

In [ ]:
df_marketing.head()

In [ ]:
df_marketing.info()
df_marketing.nunique()

Archivo de dataset clean

In [ ]:
df_marketing.to_csv(
    "../Datos/output/df_marketing_clean.csv",
    index=False
)

# 2.Características del cliente #

# Columnas del dataset  #

Income: Representa el ingreso anual del cliente en términos monetarios.

Kidhome: Indica el número de niños en el hogar del cliente.

Teenhome: Indica el número de adolescentes en el hogar del cliente.

Dt_Customer: Representa la fecha en que el cliente se convirtió en cliente de la empresa.

NumWebVisitsMonth: Indica la cantidad de visitas mensuales del cliente al sitio web de la empresa.

ID: Identificador único del cliente.

In [ ]:
df_customers = pd.read_excel('../Datos/raw/customer-details.xlsx')

In [ ]:
xls = pd.read_excel(
    '../Datos/raw/customer-details.xlsx',
    sheet_name=None
)

In [ ]:
""" VISTA DE LAS HOJAS DEL ARCHIVO EXCEL """

xls.keys()

In [ ]:
df_customers.shape

In [ ]:
""" CONCATENAR LAS HOJAS DEL ARCHIVO EXCEL EN UN SOLO DATAFRAME """

df_customers = pd.concat(
    xls.values(),
    ignore_index=True
)

In [ ]:
df_customers.shape

In [ ]:
df_customers.info()

In [ ]:
df_customers.head()

In [632]:
df_customers.columns

Index(['unnamed:_0', 'income', 'kidhome', 'teenhome', 'dt_customer',
       'numwebvisitsmonth', 'id'],
      dtype='str')

In [ ]:
df_customers.isnull().sum()

In [ ]:
df_customers.duplicated().sum()

In [ ]:
df_customers.columns = (
    df_customers.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_')
        .str.replace('.', '_', regex=False)
)

In [ ]:
df_customers.columns

In [ ]:
df_customers.to_csv(
    "../Datos/output/df_customers_clean.csv",
    index=False
)

In [ ]:
df_customers['id'].dtype

Comprobación de datos previas al cruce de los dataframe

In [ ]:
df_marketing['id'].unique()

In [ ]:
df_customers['id'].unique()

# Análisis descriptivo

# Cruce de datasframe

- Se observa, a primera vista que hay más clientes que a los registrados en la campaña de MK. 

¿No se ha llamado a la totalidad de los clientes?

In [ ]:
df_marketing_clean = pd.read_csv("../Datos/output/df_marketing_clean.csv")

In [ ]:
df_customers_clean = pd.read_csv("../Datos/output/df_customers_clean.csv")

In [ ]:
df_resultado = df_customers_clean.merge(
    df_marketing_clean,
    on='id',
    how='outer',
    indicator=True
)

In [ ]:
df_resultado.head()

In [ ]:
df_resultado[['_merge']].value_counts()

In [626]:
df_resultado[df_resultado['_merge'] == 'left_only'].head()

,unnamed:_0_x,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id,unnamed:_0_y,age,job,...,y,date,latitude,longitude,date_missing,date_imputed,year,month,weekday,_merge
219,119,102425,0,1,2012-11-09,25,01348114-d159-4dbf-9b3d-cf682d9150c7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
250,563,78963,1,2,2012-04-25,21,016a8a97-7549-4841-90f6-81ae7326277e,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
295,7120,136836,0,1,2014-07-29,12,01b312a8-d53e-4554-95e9-cefb9f618473,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
553,6808,21634,1,2,2013-05-31,2,0345849e-52ec-4217-8788-5c0a7235a9e2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
711,121,64631,1,2,2012-10-05,13,044183b7-4e50-4b68-9e9e-cd45f37144d5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only